FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source/FileBrowser

COPY ./SnapshotFileBrowser/SnapshotFileBrowser.csproj ./
RUN dotnet restore SnapshotFileBrowser.csproj
COPY ./SnapshotFileBrowser/ ./

WORKDIR /source
COPY ./DAL/ ./DAL/
COPY ./Helpers/ ./Helpers/
COPY ./Common/ ./Common/
COPY ./Protos/ ./Protos/
WORKDIR /source/FileBrowser 
RUN dotnet publish SnapshotFileBrowser.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /source/FileBrowser
COPY --from=build /source/FileBrowser/out .
ENTRYPOINT ["dotnet", "SnapshotFileBrowser.dll"]