version: "3.9"
services:
  file_browser:
    build:
      dockerfile: Dockerfile_SnapshotFileBrowser
      context: ./
    ports:
      - "8000:6000"
    depends_on:
      - postgres
  postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    expose:
      - "5432"
  webapi:
    build:
      dockerfile: Dockerfile_WebApi
      context: ./
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "4300:4300"
    depends_on:
      - rabbitmq
    restart: on-failure
  rabbitmq:
    image: "rabbitmq"
    hostname: rabbitmq
#    ports:
#      - "5672:5672"
    expose:
      - "5672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5672" ]
      interval: 30s
      timeout: 10s
      retries: 5